---
- hosts: master
  become: yes
  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0  
  
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - gnupg2
      - software-properties-common

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
    - swap
    - none



  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true
  - name: Ensure containerd is installed.
    package:
      name: containerd.io
      state: present

  - name: Ensure containerd is started and enabled at boot.
    service:
      name: containerd
      state: started
      enabled: true

  - name: Ensure containerd config directory exists.
    file:
      path: /etc/containerd
      state: directory
    register: containerd_dir
