---
- hosts: master
  become: yes
  tasks:
  - name: Create an Empty file for Kubeadm configuring
    copy:
      content: ""
      dest: /etc/kubernetes/kubeadm-config.yaml
      force: no

- name: Configure container runtime 
   blockinfile:
     path: /etc/kubernetes/kubeadm-config.yaml
     block: |
        kind: ClusterConfiguration
        apiVersion: kubeadm.k8s.io/v1beta3
        networking:
          podSubnet: "10.244.0.0/16"
        ---
        kind: KubeletConfiguration
        apiVersion: kubelet.config.k8s.io/v1beta1
        runtimeRequestTimeout: "15m"
        cgroupDriver: "systemd"
        systemReserved:
          cpu: 100m
          memory: 350M
        kubeReserved:
          cpu: 100m
          memory: 50M
        enforceNodeAllocatable:
        - pods

  - name: Initialize the cluster
    shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml >> cluster_initialized.log
    args:
      chdir: /home/sidor
      creates: cluster_initialized.log

  - name: Create .kube directory
    become: yes
    become_user: sidor
    file:
      path: $HOME/.kube
      state: directory
      mode: 755

  - name: Copy admin.conf to User's kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/sidor/.kube/config
      remote_src: yes
      owner: sidor

  - name: Initialize the cluster CLUSTER
    become: yes
    shell: mkdir -p $HOME/.kube

  - name: Initialize the cluster CLUSTER
    become: yes
    shell: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

  - name: Initialize the cluster CLUSTER 1
    become: yes
    shell: mkdir -p $HOME/.kube

  - name: Initialize the cluster CLUSTER 2
    become: yes
    shell: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

  - name: Initialize the cluster CLUSTER 3
    become: yes
    shell: mkdir -p $HOME/.kube

  - name: Install Pod Network

    become: yes
    shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.log
    args:
      chdir: $HOME
      creates: pod_network_setup.log
